### PR TITLE
Tim add model builder

### PR DESCRIPTION
**Pull request by tim-johnson-sage**

### CODE REVIEW

**Comment by aeliasage** [comment]
@timj-at-sage I think you're missing files in this pull request. I see references to a project that wasn't included in the commits.

**Review by aeliasage — CHANGES_REQUESTED** [review]
Check to make sure all of the files are committed as expected for this branch.

**Comment by tim-johnson-sage** [comment]
Project has been added.

**Review by aeliasage — APPROVED** [review]
LGTM

**Review by aeliasage — APPROVED** [review]

**Pull request merged**
